#  Metirc
- 모델 성능 평가지표
- 실제값과 모델에 의해 예측된 값을 비교하여 모델의 성능을 측정
- 모델 평가 목적
    - 최적의 모델을 찾기 위해

- 회귀 문제 성능측정
    - 실제값과 예측값의 차이를 측정

# 회귀 문제 성능측정

## 당뇨병 진행 예측
- 당뇨병 진행도를 예측하는 데이터셋

In [2]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()
diabetes.data, diabetes.target

(array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
   

In [3]:
data = diabetes.data
target = diabetes.target

In [4]:
data.shape

(442, 10)

In [5]:
target.shape

(442,)

In [6]:
print(target.min())
print(target.max())

25.0
346.0


## 학습셋과 검증셋 분리

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_vaild, y_train, y_vaild = train_test_split(data, target , test_size = 0.2)

## Linear Regression 모델을 이용한 학습 및 예측
$$
y = w_1 x_1 + ... + w_{10} x_{10} + w_0
$$

- w : 가중치
- b : 편향

In [11]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [13]:
model.fit(x_train, y_train)

LinearRegression()

In [14]:
y_vaild_predict = model.predict(x_vaild)

In [15]:
y_vaild_predict

array([ 79.13407326, 155.41046528,  95.10604887, 162.98164239,
       105.63574123,  52.12573478, 166.2617315 , 137.88953094,
       117.10344338, 118.2568697 , 217.10185386, 115.42161371,
       144.20024586, 136.71206053,  89.91895577, 249.7097825 ,
        91.95923515, 172.82361083,  68.20170178, 187.3082115 ,
       220.35525345, 165.9083564 ,  83.53030103, 115.54307091,
       111.08581223,  74.7039444 , 142.34119672,  46.83326841,
       183.85531122, 177.28705175, 197.91716117,  71.68046274,
       208.86689052, 110.55899563,  93.04978491, 275.73892743,
       123.00134522, 158.86602707, 194.92176798, 160.56965927,
       180.50956445,  72.72621962, 169.05571163, 194.53917631,
       160.0361574 , 139.57734694, 134.33349281, 176.14880745,
       222.99870988, 134.13304903, 117.83857782, 156.47749273,
       192.03419075,  64.09481959, 146.57023589, 255.91364219,
       204.95539584, 197.19614747, 270.04996861,  81.37327344,
       201.4608731 , 155.92783571, 172.69419755, 119.16

## 회귀 평가 지표


### MSE(Mean Squared Error)
$$
MSE = \frac{1}{n}{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}
$$
- 실제값과 예측값의 차이를 제곱해서 평균화
- 이상치에 민감
- 직관적이지 못하다.
- 손실함수로 주로 사용한다.

In [18]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_vaild_predict, y_vaild)
print(mse)

2880.354743460283


### RMSE(Root Mean Squared Error)
$$
RMSE = \sqrt{\frac{1}{n}{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}}
$$
- MSE에 루트
- 이상치 민감


In [20]:

# 방법1
import numpy as np
print(np.sqrt(mse))

# 방법2
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html
rmse = mean_squared_error(y_vaild_predict, y_vaild, squared=False)
print(rmse)

53.66893648527314
53.66893648527314


### MAE(Mean Absolute Error)
$$
MAE = \frac{1}{n}{\sum_{i=1}^{n}|y_i-\hat{y}_i|}
$$
- 실제값과 예측값의 차이를 절대값으로 변환해서 평균화
- 직관적이다.

In [21]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_vaild_predict, y_vaild,)
mae

42.77875185774842

### MAPE (Mean Absolute Percentage Error)
$$
MAPE = \frac{100}{n}{\sum_{i=1}^{n}\frac{|y_i-\hat{y}_i|}{y_i}}
$$
- 실제값에 대한 절대오차 비율의 평균을 퍼센트로 표현

In [22]:

# 방법1
def mape(true,pred):
   return np.mean(np.abs((true - pred) / true))
print(mape(y_vaild_predict, y_vaild))

# 방법2
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_vaild_predict, y_vaild)

0.2932169608397043


0.2932169608397043

### SMAPE (Symmetric Mean Absolute Percentage Error)
$$
SMAPE = \frac{100}{n}{\sum_{i=1}^{n}\frac{|y_i-\hat{y_i}|}{{|y_i|}+|\hat{y_i}|}}
$$
- 기존 mape의 단점을 보완한것
- MAPE와 다른점은 각 실제값과 예측값을 절대값으로 변경후 핪으로 나눈다.
- MAPE와 다르게 실제값에 0이 존재해도 계산이 가능하다.
- 실제값보다 예측값이 크거나 작을수도있다.
- 예측값이 실제값보다 작을때, 분모가 작아지기 때문에 오차가 커지게 된다. (과소추정에 대한 패널티가 줄수가 있다.)


In [24]:
def smape(true,pred):
   error =  np.abs(true - pred) / (np.abs(true) + np.abs(pred))
   return np.mean(error)
smape(y_vaild_predict, y_vaild)

0.15836023472627597

### 결정계수 R2 
- 결정계수는 실제 관측값의 분산대비 예측값의 분산을 계산하여 데이터 예측의 정확도 성능을 측정하는 지표 
- 0~1까지 수로 나타내어지며 1에 가까울수록 100%의 설명력을 가진 모델이라고 평가를 하게된다.
- R^2 =1 : 현재 가지고 있는 X변수로 Y를 100% 설명. 즉, 모든 관측치가 회귀직선에 있다.
- R^2 = 0 : 현재 가지고 있는 X변수는 Y 설명(예측)에 전혀 도움이 되지 않는다
- 사용하고 있는 X변수의 품질


$$
R^2 = \frac{SSR}{SST} =\frac{오차^2}{편차^2} =  1- \frac{SSE}{SST}
$$

- SST (Sum of Squared Total): 관측치 - 예측값
- SSE (Sum of Squared Error): 관측값 - 예측값, 즉 잔차제곱합 RSS와 같은 의미이다.
- SSR (Sum of Squares due to Regression): 예측값 - 평균값

In [27]:
from sklearn.metrics import r2_score
r2_score(y_vaild, y_vaild_predict)

0.45389365351468525